version: '3'

services:
  mongo:
    image: mongo
    container_name: database
    expose:
      - 27017
  redis:
    image: redis:alpine
    container_name: cache
    expose:
      - 6379
  api:
    container_name: api
    build: .
    command: npm start
    depends_on:
      - redis
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=3333
      - REDIS_URL="redis://cache"
      - MONGO_URI=mongodb://database:27017
    ports:
      - "3333:3333"
    volumes:
      - .:/apps/minubooks
